In [2]:
import numpy as np
import qutip as qt



In [50]:
x = qt.Qobj(np.array([[0, 1], [1, 0]]))
y = qt.Qobj(np.array([[0, -1j], [1j, 0]]))
z = qt.Qobj(np.array([[1, 0], [0, -1]]))


Ry90 = (-1j * (np.pi / 4) * y).expm()
Ry180 = (-1j * (np.pi / 2) * y).expm()
H = (1 / np.sqrt(2)) * qt.Qobj(np.array([[1, 1], [1, -1]]))
with np.printoptions(precision=3, suppress=True):
    print(f'Ry90:\n{Ry90}\n')
    print(f'Ry180:\n{Ry180}\n')
    print(f'Hadamard:\n {H}\n')
    print(f'H^2 equals Identity:\n {H * H}\n')
    print(f'Ry90 equals Hadamard:\n {Ry90 == H}\n')
    

Ry90:
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0.707 -0.707]
 [ 0.707  0.707]]

Ry180:
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0. -1.]
 [ 1.  0.]]

Hadamard:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.707  0.707]
 [ 0.707 -0.707]]

H^2 equals Identity:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1. -0.]
 [-0.  1.]]

Ry90 equals Hadamard:
 False



In [ ]:
X = qt.Qobj(np.array([[0, 1], [1, 0]]))
Y = qt.Qobj(np.array([[0, -1j], [1j, 0]]))
Z = qt.Qobj(np.array([[1, 0], [0, -1]]))
I = qt.Qobj(np.array([[1, 0], [0, 1]]))

#print out the matrices for the 16 two-qubit Pauli operators
with np.printoptions(precision=1, suppress=True):
    print(f'II:\n{qt.tensor(I, I)}\n')
    print(f'IX:\n{qt.tensor(I, X)}\n')
    print(f'IY:\n{qt.tensor(I, Y)}\n')
    print(f'IZ:\n{qt.tensor(I, Z)}\n')
    print(f'XI:\n{qt.tensor(X, I)}\n')
    print(f'XX:\n{qt.tensor(X, X)}\n')
    print(f'XY:\n{qt.tensor(X, Y)}\n')
    print(f'XZ:\n{qt.tensor(X, Z)}\n')
    print(f'YI:\n{qt.tensor(Y, I)}\n')
    print(f'YX:\n{qt.tensor(Y, X)}\n')
    print(f'YY:\n{qt.tensor(Y, Y)}\n')
    print(f'YZ:\n{qt.tensor(Y, Z)}\n')
    print(f'ZI:\n{qt.tensor(Z, I)}\n')
    print(f'ZX:\n{qt.tensor(Z, X)}\n')
    print(f'ZY:\n{qt.tensor(Z, Y)}\n')
    print(f'ZZ:\n{qt.tensor(Z, Z)}\n')



II:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

IX:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

IY:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.+0.j 0.-1.j 0.+0.j 0.-0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]]

IZ:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0. -1.]]

XI:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

XX:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype

In [9]:
qt.sigmax() @ qt.sigmap() @qt.sigmam() + qt.sigmap() @ qt.sigmam() @ qt.sigmax()


Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1.]
 [1. 0.]]